CREATE USER BANK IDENTIFIED BY bank;
GRANT ALL PRIVILEGES TO BANK;

ALTER USER BANK DEFAULT TABLESPACE users;
ALTER USER BANK QUOTA UNLIMITED ON users;

SELECT username FROM dba_users WHERE username = 'BANK';
SELECT username FROM dba_users WHERE username = 'practice';